snap-board:
    ip: 127.0.0.1
    port: 7147

firmware:
    fpg_file: /home/pi/albatros2_daq/firmware/albatros_dual_input_gbe_2019-10-24_0132.fpg

synthesizer:
    input: Internal
    frequency: 10

adcs:
   adc_digital_gain: 2
   powerdown_unused_adcs: True

pfb:
    fftshift: 0xffffffff

test-vector-generator:
    enable: False
    data: test_data.npy

xcorr:
    accumulation_length: 393216

packetiser:
    bits: 1
    max_bytes_per_packet: 1300
    channels: 500:992
    channel_coeffs: 500:746:75

ethernet:
    destination_ip: 192.168.2.200
    destination_port: 4321
    destination_mac: 0xb827eb153fc4

baseband:
    drive_safety: 22.5
    file_size: 500
    directory_name: baseband

spectra:
    diff: False
    compress: bzip2
    file_size: 100
    directory_name: spectra

log_level: 20

log_directory: /home/pi/logs/
